FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app
COPY pom.xml .

COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN addgroup -S bankgroup && adduser -S bankuser -G bankgroup
COPY --from=builder --chown=bankuser:bankgroup /app/target/*.jar app.jar
USER bankuser
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]